package tcg.komkit.server.command.json;

import com.fasterxml.jackson.annotation.JsonFormat;

@JsonFormat(shape = JsonFormat.Shape.NUMBER)
public enum EStatusCode {
	NOERROR,
	USER_NOTREGISTERED,
	PERMISSION_DENIED,
	INVALID_REQUEST,
	INVALID_RESPONSE,
	INVALID_COMMUNITY,
	INVALID_STRUCTURE,
	INVALID_NOTIFICATION,
	INVALID_BROADCAST,
	INVALID_USER,
	INVALID_USER_OR_PASSWORD,
	INVALID_AUTH_TOKEN,
	INVALID_REFERRAL_CODE,
	INVALID_REFERRAL_COMMUNITY,
	INVALID_REFERRAL_STRUCTURE,
	INVALID_REFERRAL_USER,
	INVALID_PARENT_STRUCTURE,
	FAIL_STRUCTURE_CREATION,
	FAIL_USER_REGISTRATION,
	FAIL_USER_UPDATE,
	FAIL_USER_ONBOARDING,
	FAIL_USER_OWNERSHIP,
	FAIL_REFERRAL_CODE_CREATION,
	FAIL_REFERRAL_CODE_VERIFICATION,
	FAIL_DATABASE_UPDATE,
	FAIL_NOTIFICATION_SENDING,
	USER_BANNED,
	USER_EXIST,
	STRUCTURE_EXIST

}
